name: metagwas_r_plotting
channels:
    - bioconda
    - conda-forge
    - r
dependencies:
    - r-base
    - r-tidyverse
    - r-ggplot2
    - r-ggrepel
    - bioconductor-ggbio
    - bioconductor-genomicranges
